export const studentsData = {
    "count": 1323,
    "next": "https://api.instincthub.com/api/v1/assessment/cohort_students/?limit=10&offset=10",
    "previous": null,
    "results": [
        {
            "user": {
                "id": 447,
                "first_name": "Oghenekevwe",
                "last_name": "Noah-Olatoye",
                "email": "kaykuale@gmail.com",
                "username": "Kaytoye",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Afe Babalola University",
            "expected_income": null,
            "course": "Anatomy",
            "faculty": "Medicine & Pharmacy",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2015,
            "finished_year": 2020,
            "commitment_hours": 10,
            "have_laptop": true,
            "network": "MTN",
            "knowledge_scale": 6,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-05T01:43:25.087054+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-05T01:43:25.087079+01:00"
        },
        {
            "user": {
                "id": 449,
                "first_name": "Timilehin",
                "last_name": "Olatunji",
                "email": "timmylehin.oo@gmail.com",
                "username": "olatimmy",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "University of Lagos",
            "expected_income": null,
            "course": "Mechanical Engineering",
            "faculty": "Faculty of Engineering",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2017,
            "finished_year": 2023,
            "commitment_hours": 10,
            "have_laptop": true,
            "network": "Airtel",
            "knowledge_scale": 10,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-05T08:04:04.418229+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-05T08:04:04.418271+01:00"
        },
        {
            "user": {
                "id": 452,
                "first_name": "Victoria",
                "last_name": "Santos",
                "email": "Santosakarume@gmail.com",
                "username": "Santos",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Lagos State University",
            "expected_income": null,
            "course": "Physics",
            "faculty": "Science & Technology",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2018,
            "finished_year": 2023,
            "commitment_hours": 10,
            "have_laptop": true,
            "network": "MTN",
            "knowledge_scale": 10,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-05T15:16:39.254875+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-05T15:16:39.254908+01:00"
        },
        {
            "user": {
                "id": 455,
                "first_name": "Tosin",
                "last_name": "Alo",
                "email": "Oluwatosinalo8@gmail.com",
                "username": "Tee8",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Babcock University",
            "expected_income": null,
            "course": "Mass Communication",
            "faculty": "Mass communication",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2012,
            "finished_year": 2025,
            "commitment_hours": 10,
            "have_laptop": false,
            "network": "others",
            "knowledge_scale": 8,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": false,
            "updated": "2022-07-05T16:07:19.181509+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-05T16:07:19.181577+01:00"
        },
        {
            "user": {
                "id": 457,
                "first_name": "Makinde",
                "last_name": "Sodiq",
                "email": "myskillzcamp@gmail.com",
                "username": "Makinde",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Obafemi Awolowo University",
            "expected_income": null,
            "course": "Computer Science",
            "faculty": "Science & Technology",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2015,
            "finished_year": 2023,
            "commitment_hours": 10,
            "have_laptop": true,
            "network": "MTN",
            "knowledge_scale": 8,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-05T16:31:01.318215+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-05T16:31:01.318254+01:00"
        },
        {
            "user": {
                "id": 454,
                "first_name": "Adekunle",
                "last_name": "Adebayo",
                "email": "stanley.adebayo@gmail.com",
                "username": "qunlay28",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Ago egba university",
            "expected_income": null,
            "course": "Yoruba",
            "faculty": "Linguistics",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2020,
            "finished_year": 2023,
            "commitment_hours": 10,
            "have_laptop": true,
            "network": "MTN",
            "knowledge_scale": 10,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-05T16:31:13.983396+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-05T16:31:13.983452+01:00"
        },
        {
            "user": {
                "id": 456,
                "first_name": "DAMILOLA",
                "last_name": "ADEKOYA",
                "email": "adekoyadamilola75@yahoo.com",
                "username": "MARK II",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Federal University Oye Ekiti",
            "expected_income": null,
            "course": "Mechanical Engineering",
            "faculty": "Medicine & Pharmacy",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2009,
            "finished_year": 2022,
            "commitment_hours": 10,
            "have_laptop": true,
            "network": "MTN",
            "knowledge_scale": 8,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-05T16:43:39.838302+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-05T16:43:39.838341+01:00"
        },
        {
            "user": {
                "id": 467,
                "first_name": "Hameed",
                "last_name": "Alabi",
                "email": "alabihameeda@gmail.com",
                "username": "Hameed",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Bayero University Kano",
            "expected_income": null,
            "course": "Software Engineering",
            "faculty": "Computing",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2018,
            "finished_year": 2022,
            "commitment_hours": 12,
            "have_laptop": false,
            "network": "MTN",
            "knowledge_scale": 10,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-06T12:01:01.615131+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-06T12:01:01.615176+01:00"
        },
        {
            "user": {
                "id": 483,
                "first_name": "Jafar",
                "last_name": "Abdulwaheed",
                "email": "jafar.abdulwaheed@gmail.com",
                "username": "NobleGenius",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Bayero University Kano",
            "expected_income": null,
            "course": "Computer Science",
            "faculty": "Faculty of Computing",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2018,
            "finished_year": 2023,
            "commitment_hours": 4,
            "have_laptop": true,
            "network": "Airtel",
            "knowledge_scale": 10,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-06T12:16:57.708235+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-06T12:16:57.708286+01:00"
        },
        {
            "user": {
                "id": 484,
                "first_name": "AFOLAKE",
                "last_name": "ADEFIOYE",
                "email": "adefioyeafolake60@gmail.com",
                "username": "Adefioye Afolake",
                "verified": false,
                "is_staff": false
            },
            "course_choice": [],
            "cohort": [],
            "in_school": null,
            "employed": null,
            "job_search": null,
            "school": "Olabisi Onabanjo University",
            "expected_income": null,
            "course": "Chemistry with Education",
            "faculty": "education",
            "influencer": null,
            "where": null,
            "level": 10,
            "entry_year": 2017,
            "finished_year": 2021,
            "commitment_hours": 8,
            "have_laptop": true,
            "network": "MTN",
            "knowledge_scale": 10,
            "valid_id": null,
            "valid_id_ppoi": "(0.5, 0.5)",
            "promotion_email": false,
            "share_data": true,
            "updated": "2022-07-06T12:17:13.179000+01:00",
            "campus_lead": null,
            "timestamp": "2022-07-06T12:17:13.179038+01:00"
        }
    ]
}

export const cohortData = {
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 3,
            "title": "TDN 3.2",
            "from_date": "2023-09-01",
            "to_date": "2023-11-30",
            "timestamp": "2023-01-11T05:09:16.613193+01:00"
        },
        {
            "id": 2,
            "title": "TDN 3.1",
            "from_date": "2023-06-01",
            "to_date": "2023-08-31",
            "timestamp": "2023-01-11T05:08:14.608055+01:00"
        }
    ]
}

export const statsData = {
    "message": "This shows student analytics ",
    "data": {
        "total_students": 1323,
        "total_students_last_28_days": 38,
        "total_university_applicants": 527,
        "total_university_applicants_last_28_days": 17,
        "total_students_meets_expectation": 1767,
        "total_students_meets_expectation_last_28_days": 360
    }
}